apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../overlays/production
images:
  - name: chat
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/chat-ms # {"$imagepolicy": "flux-system:chat:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:chat:tag"}
  - name: editor
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/editor-ms # {"$imagepolicy": "flux-system:editor:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:editor:tag"}
  - name: match
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/match-ms # {"$imagepolicy": "flux-system:match:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:match:tag"}
  - name: question
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/question-ms # {"$imagepolicy": "flux-system:question:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:question:tag"}
  - name: user
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/user-ms # {"$imagepolicy": "flux-system:user:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:user:tag"}
  - name: video-chat
    newName: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/video-chat-ms # {"$imagepolicy": "flux-system:video-chat:name"}
    newTag: 1.0.6 # {"$imagepolicy": "flux-system:video-chat:tag"}
