apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  
replicas:
- name: chat
  count: 2
- name: editor
  count: 2
- name: match
  count: 2
- name: question
  count: 2
- name: user
  count: 2
- name: video-chat
  count: 1
